[package]
name = "iceberg-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }

# Bring the logic crate into the UI
iceberg-core = { path = "../core" }
